# 

In [1]:
import random

SalaryList = [random.randint(50000,100000) for _ in range(1_000_000)]

In [11]:
import statistics

In [13]:
%%timeit
statistics.mean(SalaryList)

423 ms ± 62.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [15]:
import numpy as np

In [17]:
%%timeit
np.mean(SalaryList)

68.9 ms ± 5.26 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [31]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [33]:
arr[2]

3

In [21]:
arr.mean()

2.5

In [25]:
job_title = np.array(['Data Analyst','Data Scientist','Data Engineer','Machine Learning Engineer'])
base_salaries = np.array([60000,80000,75000,90000])
bonus_rate = np.array([.05,.1,.08,.12])

In [27]:
total_salaries = base_salaries * (1 + bonus_rate)

total_salaries

array([ 63000.,  88000.,  81000., 100800.])

In [29]:
np.mean(total_salaries)

83200.0

In [35]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
arr2[1,2]

6

In [41]:
arr2[1][2]

6

In [45]:
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [49]:
arr3[1,0,2]

9

In [51]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [53]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [55]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [57]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [59]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [61]:
np.full((2,4),8)

array([[8, 8, 8, 8],
       [8, 8, 8, 8]])

In [63]:
np.random.rand(2,7)

array([[0.23494325, 0.00444926, 0.41456649, 0.50678858, 0.1491128 ,
        0.21656178, 0.50625471],
       [0.99706223, 0.32548886, 0.23953538, 0.62946413, 0.4669198 ,
        0.65098943, 0.37455567]])

In [65]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [67]:
arr.shape

(2, 5)

In [69]:
arr.size

10

In [71]:
arr.dtype

dtype('int32')

In [73]:
arr.itemsize

4

In [75]:
arr.nbytes

40

In [77]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [79]:
arr[-1]

array([ 6,  7,  8,  9, 10])

In [81]:
arr[1][2]

8

In [83]:
arr[1,2]

8

In [87]:
arr[0:2, 1:3] 

array([[2, 3],
       [7, 8]])

In [89]:
arr[:, 2]

array([3, 8])

In [91]:
arr[0, :]

array([1, 2, 3, 4, 5])

In [93]:
arr[::-1]

array([[ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

In [97]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [99]:
arr + 10

array([11, 12, 13, 14])

In [101]:
arr * 2

array([2, 4, 6, 8])

In [103]:
arr **2

array([ 1,  4,  9, 16])

In [105]:
arr - 1

array([0, 1, 2, 3])

In [107]:
arr/3

array([0.33333333, 0.66666667, 1.        , 1.33333333])

In [109]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [111]:
np.exp(arr)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [113]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [115]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [117]:
np.cos(arr)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [119]:
arr.sum()

10

In [121]:
arr.mean()

2.5

In [123]:
arr.min()

1

In [125]:
arr.max()

4

In [127]:
arr.std()

1.118033988749895

In [129]:
arr.var()

1.25

In [131]:
arr.argmax()

3

In [133]:
arr.argmin()

0

In [135]:
arr = np.arange(1,9)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [137]:
arr.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [141]:
arr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [143]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [145]:
arr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [147]:
arr.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [151]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [155]:
np.vstack((arr1, arr2))

array([[1, 2, 3],
       [4, 5, 6]])

In [157]:
np.hstack((arr1, arr2))

array([1, 2, 3, 4, 5, 6])

In [159]:
np.column_stack((arr1, arr2))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [161]:
"Farida EmadEldin Elsayed".split(" ")

['Farida', 'EmadEldin', 'Elsayed']

In [163]:
arr = arr.ravel()
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [169]:
np.split(arr,4)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]

In [171]:
np.array_split(arr,4)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]

In [173]:
arr > 3

array([False, False, False,  True,  True,  True,  True,  True])

In [177]:
arr[arr > 3]

array([4, 5, 6, 7, 8])

In [181]:
np.random.rand(2,2)

array([[0.23440234, 0.59493787],
       [0.33058418, 0.46382859]])

In [185]:
np.random.seed(42)
np.random.rand(2,2)

array([[0.37454012, 0.95071431],
       [0.73199394, 0.59865848]])

In [187]:
np.random.randint(1,10, (2,2))

array([[7, 3],
       [7, 8]])

In [191]:
A = np.array([[1,2],[4,5]])
B = np.array([[1,2],[4,5]])

In [193]:
A

array([[1, 2],
       [4, 5]])

In [195]:
B

array([[1, 2],
       [4, 5]])

In [197]:
np.dot(A,B)

array([[ 9, 12],
       [24, 33]])

In [201]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [205]:
A = np.array([[1],[2],[3]])
B = np.array([4,5,6])

In [207]:
A

array([[1],
       [2],
       [3]])

In [209]:
A.shape

(3, 1)

In [211]:
B

array([4, 5, 6])

In [213]:
B.shape

(3,)

In [215]:
A + B

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [217]:
np.unique([1,1,1,2,2,3,3,3])

array([1, 2, 3])

In [219]:
arr = np.array([1,2,3,4,5], dtype=np.int8)
arr

array([1, 2, 3, 4, 5], dtype=int8)

In [221]:
arr.dtype

dtype('int8')

In [227]:
arr = np.array([1,"2",3.2,4,5], dtype="object")
print(type(arr[0]))
print(type(arr[1]))
print(type(arr[2]))

<class 'int'>
<class 'str'>
<class 'float'>


In [229]:
arr = np.array([1,"2",3.2,4,5], dtype="float")
print(type(arr[0]))
print(type(arr[1]))
print(type(arr[2]))

<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>


In [231]:
arr[1]

2.0

In [233]:
arr = np.array([1,"2",3.2,4,5])
print(type(arr[0]))
print(type(arr[1]))
print(type(arr[2]))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [235]:
arr[0]

'1'