In [9]:
import numpy as np

In [11]:
# random decimal number between 1 and 10
a = np.random.uniform(1,10)
a

7.795373486895956

In [13]:
# 5 random decimal number between 1 and 10
z = np.random.uniform(1,10,5)
z

array([3.74109196, 2.42843294, 3.26125913, 6.72961481, 1.20611715])

In [21]:
# three random numbers between 0 to 1 
x = np.random.random(3)
x

array([0.60726489, 0.68468918, 0.58216927])

In [23]:
# three random numbers between 0 to 1 
x = np.random.rand(3)
x

array([0.18518476, 0.48999378, 0.87000938])

In [25]:
# matrix of 2x3 of random numbers between 0 & 1
a = np.random.random((2,3))
a

array([[0.33139428, 0.67675855, 0.35120328],
       [0.04545948, 0.53413461, 0.06786331]])

In [37]:
allList = []
for j in list([list(i) for i in a]):
    allList.extend(j)
allList = [i*1000 for i in allList]
allList

[331.3942775241465,
 676.7585474488047,
 351.2032828932967,
 45.45948482889317,
 534.1346081814058,
 67.86331184511451]

In [39]:
roundList = [np.round(i) for i in allList]
roundList

[331.0, 677.0, 351.0, 45.0, 534.0, 68.0]

In [41]:
roundList = [np.round(i,2) for i in allList]
roundList

[331.39, 676.76, 351.2, 45.46, 534.13, 67.86]

In [43]:
np.round(15.1)

15.0

In [45]:
np.round(15.9)

16.0

In [49]:
np.floor(15.1),np.floor(15.9)

(15.0, 15.0)

In [51]:
np.ceil(15.1),np.ceil(15.9)

(16.0, 16.0)